social_media = [
    "facebook.com",
    "twitter.com",
    "instagram.com",
    "linkedin.com",
    "youtube.com",
    "youtu.be",
    "twitch.tv",
    "reddit.com",
    "redd.it",
    "pinterest.com",
    "tiktok.com",
    "snapchat.com",
    "whatsapp.com",
    "telegram.com",
    "telegram.org",
    "discord.com",
    "viber.com",
    "line.me",
    "kakaotalk.com",
    "wechat.com",
    "qq.com",
    "weibo.com",
    "t.me",
    "x.com",
    "substack.com",
    "parler.com",
    "rumble.com",
    "gab.com",
    "truthsocial.com",
    "4chan.org",
    "bitchute.com",
]

search_engines = [
    "google.com",
    "bing.com",
    "yahoo.com",
    "duckduckgo.com",
    "baidu.com",
    "yandex.com",
    "goo.gl",
]


other = [
    "amazon.com",
    "amzn.to",
    "amazon.in",
    "wordpress.com",
    "tinyurl.com",
    "paypal.me",
    "paypal.com",
    "gettr.com",
    "dlive.tv",
    "lbry.com",
    "minds.com",
    "bit.ly",
    "t.co",
    "odysee.com",
    "change.org",
    "gmx.net",
    "soundcloud.com",
    "doi.org",
    "github.com",
    "rebrand.ly",
    "wa.me",
    "ift.tt",
    "seeclickfix.com",
    "linktre.ee",
    "brslots.win",
]